### ISSUE TITLE
1:163: error: element "svg" missing required attribute "baseProfile"

### ISSUE THREAD

**Issue by zaiemv** [authindicators/svg-ps-converters#5]
The error in the title shows up in the [BIMI Look-up tool](https://bimigroup.org/bimi-generator/) when we do a search. We have now attempted this using the Standalone GUI tool for MacOS, The Adobe illustrator export script, as well as manually editing the original SVG file we exported from illustrator without the script. The error shows up every time regardless of what which method we follow. Here's a [link to SVG format logo ](https://www.anaplan.com/wp-content/uploads/2021/06/anaplan_a_icon_original_tiny_ps_tiny_ps-jsxscript.svg)

**Comment by zaiemv** [comment]
And to add one more thing to this, we have made sure that the baseProfile attribute is there by opening the SVG in a text editor after attempting each method.

**Comment by EmailKarma** [comment]
There are missing elements in the logo linked to in this item - the baseProfile="tiny-ps" tag is missing. 

Using the SVG conversation tools provided by the BIMI Group should be able to resolve this issue: https://bimigroup.org/svg-conversion-tools-released/

**Comment by zaiemv** [comment]
I just figured it out. Turns out wordpress was removing the baseprofile tag when we uploaded the image. Thanks for the response.
